[package]
name = "dev-syn/ui-presets"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
[place]
shared-packages = "game.ReplicatedStorage.Packages"
dev-packages = "game.ReplicatedStorage.Packages"
[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
[dependencies]
GoodSignal = "stravant/goodsignal@0.2.1"