[package]
name = "dev-syn/ui-presets"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true
[place]
shared-packages = "game.ReplicatedStorage.Packages"
[dependencies]
goodsignal = "stravant/goodsignal@0.2.1"